services:
    bookings.invoice_create_listener:
        class: BookingsBundle\EventListener\CreateInvoiceListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    bookings.invoice_update_listener:
        class: BookingsBundle\EventListener\CreateInvoiceListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
