<?php

namespace AppBundle\Repository;

/**
 * EmailTemplatesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplatesRepository extends \Doctrine\ORM\EntityRepository
{
}
