<?php

namespace AppBundle\Repository;

/**
 * EntityBankRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityBankRepository extends \Doctrine\ORM\EntityRepository
{
}
