# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.geo_service:
        class: AppBundle\Service\GeoService
        arguments: ["@service_container"]

    app.settings_service:
        class: AppBundle\Service\SettingsService
        arguments: ["@service_container"]